# -*- coding: utf-8 -*-
"""line_bot2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/165WqbdSLeT9Gn5dm1NbJ1RpyfEZXqv2X
"""


from flask import Flask, request,abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, TextSendMessage
import pya3rt
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
run_with_ngrok(app)

linebot_api = LineBotApi('2GLAiQyYLall23wKhFiOJqx2VnA/qZdMidVO7+5+IXTDh1V7fOFYYOjDo5v7bXWLJmq6Av97Zm2DILSuSt+wZ5Ca1vAZVGZoZr7gJUXrMRXw7p9tGU/HayCpdMGVSLyidvRIQdU4D2MKWR4aU7MaYwdB04t89/1O/w1cDnyilFU=')
handler = WebhookHandler('aefa06e2126145f7a4448ec5bc31bf2a')

@app.route("/callback",methods=['POST'])
def callback():
    signature = request.headers["X-Line-Signature"]
    body = request.get_data(as_text=True)

    try:
        handler.handle(body,signature)
    except InvalidSignatureError:
        abort(400)
    return("OK")

@handler.add(MessageEvent,message=TextMessage)
def handle_message(event):
    ai_message = talk_ai(event.message.text)
    linebot_api.reply_message(event.reply_token,TextSendMessage(text=ai_message))


def talk_ai(word):
    apikey = "DZZ8Iwyo6fo6lY7JVUWSqgqrgze4IbBz"
    client = pya3rt.TalkClient(apikey)
    reply_message = client.talk(word)
    return reply_message['results'][0]['reply']

if __name__ =='__main__':
    app.run()